version: '3.8'

services:
  app:
    image: openjdk:23-jdk-slim
    container_name: ordermanagement
    volumes:
      - C:/Users/devan/Desktop/OrderManagementSystem/OrderManagement/build/libs/OrderManagement-0.0.1-SNAPSHOT.jar:/app.jar # Path to your built JAR file
    command: ["java", "-jar", "/app.jar"]
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ordermanagement.chsgu2y0clq7.ap-south-1.rds.amazonaws.com:3306/ordermanagementdb
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 
    depends_on:
      - mysql

  mysql:
    image: 'mysql:latest'
    container_name: local-mysql
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
